apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "proglog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "proglog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "proglog.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "proglog.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ include "proglog.fullname" . }}
      labels: {{ include "proglog.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ include "proglog.fullname" . }}-config-init
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |-
              ID=$(echo $HOSTNAME | rev | cut -d- -f1 | rev)
              cat > /var/run/proglog/config.yaml <<'EOD'
              data-dir: /var/run/proglog/data
              rpc-port: {{.Values.rpcPort}}
              bind-addr: HOSTNAME_PLACEHOLDER
              bootstrap: BOOTSTRAP_PLACEHOLDER
              EOD
              sed -i "s/HOSTNAME_PLACEHOLDER/$HOSTNAME.proglog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}/" /var/run/proglog/config.yaml
              sed -i "s/BOOTSTRAP_PLACEHOLDER/$([ $ID = 0 ] && echo true || echo false)/" /var/run/proglog/config.yaml
              sed -i 's/^[[:space:]]*//' /var/run/proglog/config.yaml
              if [ $ID != 0 ]; then echo "start-join-addrs: \"proglog-0.proglog.{{.Release.Namespace}}.svc.cluster.local:{{.Values.serfPort}}\"" >> /var/run/proglog/config.yaml; fi   
          volumeMounts:
            - name: datadir
              mountPath: /var/run/proglog
      containers:
        - name: {{ include "proglog.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.rpcPort }}
              name: rpc
            - containerPort: {{ .Values.serfPort }}
              name: serf
          args:
            - --config-file=/var/run/proglog/config.yaml
          readinessProbe:
            tcpSocket:
              port: {{ .Values.rpcPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.rpcPort }}
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: datadir
              mountPath: /var/run/proglog
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.storage }}
